### ISSUE TITLE
No corresponding sources for third-party binaries

### ISSUE THREAD

**Issue by bgilbert** [jcupitt/build-win32#7]
Hi John,

The VIPS download site doesn't seem to distribute the complete corresponding source code for third-party libraries in the vips-dev ZIP and the nip2 installer.  For vips-dev this is technically only required for the LGPL libraries (LGPLv2.1 section 4).  nip2 is GPL and has GPL dependencies, so [under the FSF's interpretation of the GPL](http://www.gnu.org/licenses/gpl-faq.html#GPLStaticVsDynamic), source is required even for the permissively-licensed libraries.

I'm not claiming that the missing source is currently harming anybody, and fixing it is sort of painful.  (For OpenSlide on Windows, each binary build has to ship alongside a 60 MB source ZIP that no one actually wants, and you have many more dependencies than we do.)  But it is a license violation nonetheless.

**Comment by jcupitt** [comment]
You're right, it's a violation, I was hoping no one would complain :( 

I'll have a look at fixing it.

**Comment by bgilbert** [comment]
I'd think those sources would be available from the places you got the binaries.  The GTK Windows download pages, for example, do have links to the corresponding sources.

**Comment by jcupitt** [comment]
I've added some more. I'm not sure I have all the indirect dependencies though. I'm inclined to leave it there.

**Comment by bgilbert** [comment]
AFAICT, the remaining issues are these:

- libgomp.  I think this could be removed from the binary distribution, since nothing is linked with it.
- iconv, whose sources are available on the GTK Windows page.
- The GCC DLLs, which are a thorny problem.  I don't think the GCC Runtime Library Exception on the DLLs will help you here, because the GPL on nip2 still insists on complete sources.  The GPL's system library exception doesn't help when you're the one distributing the libraries.  Maybe you could just throw in the source debs for your mingw cross-compiler?

Thanks for fixing this.

**Comment by jcupitt** [comment]
I've added iconv, thanks for that. 

I removed libgomp and libgfortran from the -dev bundle, thanks again.

The cross-compiler is just gcc built as a cross-compiler, mingw doesn't really exist any more, so I've put the gcc sources there too. It includes the libstdc++ sources, obviously. 

I think we probably still fail a strict interpretation of the GPL. It requires us (I think?) to include not just sources, but all patches and the complete build system as well. The iconv DLL I'm bundling has (again, I think) been patched slightly to improve win32 behaviour, for example. 

I'm inclined to call it "good enough" and close the issue, partly due to laziness.

**Comment by bgilbert** [comment]
winpthreads, at least, still comes from MinGW-w64.

You could ensure the build system is available by tarring up the relevant build-win32 subdirectory.  The patches you're applying are already hosted on your website, which might be good enough -- or you could move them to the build-win32 repo.

As to any missing patches in the prebuilt binaries... if your upstream isn't supplying corresponding source, then yeah, not much you can do.

(Of course, for completeness, #2 is still an issue as well.)

Thanks for your patience with this.

**Comment by jcupitt** [comment]
OK, I added the minw-w64 sources. 

Off-topic, but I'm having a go at a quick proof-of-concept hack of openslide to use vips instead of cairo for compositing. I'll just do aperio read (this is the simplest, I guess?) and I'll only do enough to get it compiling and run a simple benchmark.

cairo and vips are both about the same size, according to sloccount, though of course vips has many more dependencies.

**Comment by bgilbert** [comment]
Aperio is a reasonable case for a simple performance comparison, but of course we don't actually need compositing for Aperio.  If you want to demonstrate compositing, MIRAX is a good case.  (The rendering path is not the difficult part of MIRAX, for the most part, so the implementation shouldn't be too horrible.)

This prompted me to have another look at OpenSlide's runtime performance.  In both the JPEG and JPEG-TIFF read paths, we were doing multiple rounds of pixel swizzling at different levels (in libjpeg, in libtiff, etc.).  That is now fixed, giving a 10-25% speedup in my tests.  Swizzling in other cases, particularly JP2K, is still too slow.

**Comment by jcupitt** [comment]
OK, good to know, thanks. I'll update from master. I saw the twiddling in jp2k handling, ouch. 

I'll try MIRAX as well.
